# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0002_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='is_display',
            field=models.BooleanField(default=0),
        ),
    ]
